[[bin]]
name = "PRun"
path = "Source/Library.rs"

[[bin]]
name = "Run"
path = "Source/Library.rs"

[[bin]]
name = "Inn"
path = "Source/Library.rs"

[[bin]]
name = "InnKeeper"
path = "Source/Library.rs"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "1.1.2" }

[dependencies]
clap = { features = ["derive"], version = "4.6.1" }
crossbeam-queue = "0.3.12"
futures = { version = "0.3.32" }
globset = "0.4.18"
num_cpus = { version = "1.17.0" }
once_cell = { version = "1.21.4" }
rayon = "1.12.0"
tokio = { version = "1.52.3", features = ["full"] }
walkdir = { version = "2.5.0" }

[features]
default = []

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "Library"
path = "Source/Library.rs"

[package]
autobenches = false
autobins = false
autoexamples = false
autotests = false
default-run = "Run"
description = "Run 🍺"
edition = "2024"
include = [
	"Source/**/*",
	"LICENSE",
	"README.md",
	"CHANGELOG.md",
	"build.rs",
	"Cargo.toml",
]
license-file = "LICENSE"
name = "prun"
repository = "https://github.com/PlayForm/Run.git"
version = "0.2.1"
